/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type Uint128 = string;
export interface InstantiateMsg {
  initial_slot_size: Uint128;
  sale_amount: Uint128;
  x_liquidity: Uint128;
  y_liquidity: Uint128;
}
export type ExecuteMsg =
  | {
      burn_tokens: {
        amount: Uint128;
        referrer: string;
      };
    }
  | {
      register_starting_user: {
        user: string;
      };
    }
  | {
      register2nd_referrer: {
        referrer: string;
      };
    }
  | {
      update_slot_size: {
        slot_size: Uint128;
      };
    };
export type QueryMsg =
  | {
      config: {};
    }
  | {
      user_info: {
        address: string;
      };
    }
  | {
      current_price: {};
    }
  | {
      simulate_burn: {
        amount: Uint128;
      };
    };
export type Addr = string;
export interface Config {
  owner: Addr;
  sale_amount: Uint128;
  slot_size: Uint128;
  [k: string]: unknown;
}
export type Decimal = string;
export interface PriceResponse {
  price: Decimal;
}
export interface SimulateBurnResponse {
  final_amount: Uint128;
  swapped_out: Uint128;
  virtual_slippage: Uint128;
}
export interface UserInfoResponse {
  burnable: Uint128;
  burned: Uint128;
  cap: Uint128;
  slot_size: Uint128;
  slots: Uint128;
  swapped_out: Uint128;
}
