/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */
import * as _1 from './Burndrop.client';
import * as _2 from './Burndrop.message-composer';
export declare namespace contracts {
    const Burndrop: {
        BurndropMsgComposer: typeof _2.BurndropMsgComposer;
        BurndropQueryClient: typeof _1.BurndropQueryClient;
        BurndropClient: typeof _1.BurndropClient;
    };
}
//# sourceMappingURL=index.d.ts.map